# Locate Lua 5.1 library
# This module defines
#  LUA51_FOUND, if false, do not try to link to Lua
#  LUA_LIBRARY_DIR
#  LUA_LIBRARIES
#  LUA_INCLUDE_DIR, where to find lua.h

OPTION (ENABLE_LUA_STATIC "Enable static linking lua 5.1" OFF)

FIND_PACKAGE (PkgConfig)
IF (PKG_CONFIG_FOUND)
	PKG_CHECK_MODULES (lua5.1 lua5.1>=5.1)
ENDIF (PKG_CONFIG_FOUND)

IF (lua5.1_FOUND)
	SET (LUA51_FOUND TRUE)
	SET (LUA_INCLUDE_DIR ${lua5.1_INCLUDE_DIRS})
	SET (LUA_LIBRARIES ${lua5.1_LIBRARIES})
	SET (LUA_LIBRARY_DIR ${lua5.1_LIBRARY_DIRS})
	IF (PKG_CONFIG_EXECUTABLE)
		EXECUTE_PROCESS (COMMAND ${PKG_CONFIG_EXECUTABLE} --variable=INSTALL_LMOD lua5.1
			OUTPUT_VARIABLE LUA_MODULE_DIR
			OUTPUT_STRIP_TRAILING_WHITESPACE)
	ENDIF (PKG_CONFIG_EXECUTABLE)
ELSE (lua5.1_FOUND)
	FIND_PACKAGE (Lua51 REQUIRED)
ENDIF (lua5.1_FOUND)

IF (NOT LUA_MODULE_DIR)
	SET (LUA_MODULE_DIR share/lua/5.1)
ENDIF (NOT LUA_MODULE_DIR)

IF (ENABLE_LUA_STATIC)
	FIND_LIBRARY (LUA_LIBRARY
		NAMES liblua5.1.a
		HINTS
		$ENV{LUA_DIR}
		PATH_SUFFIXES lib64 lib
		PATHS
		~/Library/Frameworks
		/Library/Frameworks
		/usr/local
		/usr
		/sw
		/opt/local
		/opt/csw
		/opt
	)

	IF (LUA_LIBRARY)
		SET (LUA_LIBRARIES ${LUA_LIBRARY} m dl)
	ENDIF (LUA_LIBRARY)
ENDIF (ENABLE_LUA_STATIC)
